# Generated by Django 3.1.2 on 2021-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210110_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='has_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
