# Generated by Django 3.1.2 on 2021-01-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wallet_has_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='has_authenticated',
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_authenticated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
